# This workflow will generate the Sphinx documentation

name: Sphinx Documentation

on:
  push:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      working-directory: ./documentation
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Generate Documentation
      working-directory: ./documentation
      run: |
        make html
    - name: Upload static files as artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: documentation/build/html/

  deploy:
    permissions:
      contents: read
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: github-pages
      url: ${{steps.deployment.outputs.page_url}}
    steps:
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
